<<<<<<< Updated upstream
initial_puzzle: [[2,0,3],[1,4,5],[7,8,6]]
strategy:
  name: LOCAL_H
  params:
    heuristic: manhattan_distance
#  step:
=======
- initial_puzzle:
  - !!set
    '[[4 8 2], [6 3 1], [5 7 0]]': null
- strategy:
  - name:
    - BPA
  - - params:
      - heuristic:
        - null
      - - step:
          - null
>>>>>>> Stashed changes
