items_file: Mochila100Elementos.txt
population_size: 100
selector:
  method:
    name: elite
crossover:
  method:
    name: multiple_point
    params:
      points_q: 3
mutation_prob: 0.005
stop_condition:
  percentage: 50
  gen_count_percentage: 10
  gen_count: 1030
  fitness_gen_count: 500



