items_file: Mochila100Elementos.txt
population_size: 12
selector:
  method:
    name: prob_tournament
    params:
      tournament_probability: 0.75
crossover:
  method:
    name: uniform
mutation_prob: 0.005
