items_file: Mochila100Elementos.txt
population_size: 10
selector:
  method:
    name: boltzmann
    params:
      initial_temp: 40
      final_temp: 5
      k: 0.05

crossover:
  method:
    name: multiple_point
    params:
      points_q: 4
mutation_prob: 0.005
stop_condition:
  percentage: 30
  gen_count_percentage: 10
  gen_count: 5000
  fitness_gen_count: 20
  time: 121



