items_file: Mochila100Elementos.txt
population_size: 100
selector:
  method:
    name: prob_tournament
    params:
      tournament_probability: 0.7
crossover:
  method:
    name: multiple_point
    params:
      points_q: 3
mutation_prob: 0.005
stop_condition:
  percentage: 30
  gen_count_percentage: 10
  gen_count: 500
  fitness_gen_count: 20
  time: 121



