items_file: Mochila100Elementos.txt
population_size: 10
selector:
  method:
    name: elite
    params:
      initial_temp: 20
      final_temp: 10
      k: 0.2
crossover:
  method:
    name: uniform



mutation_prob: 0.005
